[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name        = "ecpfs"
version     = "0.9.7"
description = ""
authors     = [
    { name = "Omar Shahbaz Khan", email = "osk@oskhan.com" }
]
readme      = "README.md"
license     = { text = "MIT OR Apache-2.0" }
requires-python = ">=3.12"

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Rust",
  "License :: OSI Approved :: MIT License",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent"
]

dependencies = [
  "numpy>=2.5.2"
]

[dependency-groups]
dev = [
  "deptry>=0.23.0",
  "maturin>=1.0"
]

[tool.maturin]
bindings = "pyo3"
python-source = "python"
module-name   = "ecpfs.ecp"
manifest-path = "ecp-py/Cargo.toml"
